name: Python application

on: [push]

jobs:
  pyCestaTest:
    runs-on: ubuntu-latest

    env:
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: 127.0.0.1

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"

    - name: test
      run: |
        python logon/src/main.py
